//write/read 24 words
#include "enclave_body_64.S"
#include "enclave_body_64.S"
#include "enclave_body_64.S"
#include "enclave_body_64.S"
#include "enclave_body_64.S"
#include "enclave_body_64.S"
#include "enclave_body_64.S"
#include "enclave_body_64.S"
//write/read 24 words
#include "enclave_body_64.S"
#include "enclave_body_64.S"
#include "enclave_body_64.S"
#include "enclave_body_64.S"
#include "enclave_body_64.S"
#include "enclave_body_64.S"
#include "enclave_body_64.S"
#include "enclave_body_64_last.S"
#go back to start of data section
CincoffsetImm c31, c31, -0xc0 //4 x 48 = 192, c0 hex
