//write/read 24 words
#include "enclave_body_64.S"
#include "enclave_body_64.S"
#include "enclave_body_64.S"
#include "enclave_body_64.S"
#include "enclave_body_64.S"
#include "enclave_body_64.S"
#include "enclave_body_64.S"
#include "enclave_body_64.S"
//write/read 24 words
#include "enclave_body_64.S"
#include "enclave_body_64.S"
#include "enclave_body_64.S"
#include "enclave_body_64.S"
#include "enclave_body_64.S"
#include "enclave_body_64.S"
#include "enclave_body_64.S"
#include "enclave_body_64_last.S"

